name: Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            mkdir -p /root/uiblocks-backend
            cd /root/uiblocks-backend

            git pull https://x-access-token:${{ secrets.GH_PAT }}@github.com/theshreyanshsingh/uiblocks-backend.git
            npm install

            pm2 stop uiblocks-backend

            npx tsc --build

            pm2 start dist/index.js --name uiblocks-backend
